// js/language.js
const langData = {
    fa: {
        // ===== صفحه اصلی (index) =====
        nav_home: "خانه",
        nav_features: "امکانات",
        nav_gallery: "تصاویر",
        nav_video: "ویدیو",
        nav_download: "دانلود",
        nav_excel: "نرم‌افزار اکسل",
        nav_contact: "تماس با ما",

        hero_title: "حسابداری <span>مانگرو</span> در گوشی شما",
        hero_desc: "همه امکانات حسابداری حرفه‌ای را به ساده‌ترین شکل ممکن در موبایل خود تجربه کنید.",
        hero_btn: "دانلود اپلیکیشن",

        feature1_title: "گزارشات دقیق",
        feature1_desc: "دسترسی به تمام گزارشات مالی، نقدی، خرید و فروش به صورت آنی.",
        feature2_title: "مدیریت زمان",
        feature2_desc: "مهلت اشخاص، چک‌های پرداختی و دریافتی با هشدارهای هوشمند.",
        feature3_title: "امنیت بالا",
        feature3_desc: "داده‌های شما با بالاترین استانداردهای امنیتی محافظت می‌شوند.",
        feature4_title: "دسترسی آسان",
        feature4_desc: "همه امکانات در گوشی شما، هر زمان و هر مکان.",

        gallery_title: "تصاویر برنامه",

        video_title: "🎥 ویدیوی معرفی نرم‌افزار",
        video_btn: "سایر آموزش‌ها",

        download_title: "📲 همین الان دانلود کن!",
        download_ios: "نسخه آیفون",
        download_ios_sub: "(به زودی)",
        download_android: "نسخه اندروید",
        download_android_sub: "دانلود از بازار",
        download_pwa: "نسخه PWA",
        download_pwa_sub: "(به زودی)",

        excel_title: "نرم افزار اکسل",
        excel_accounting: "حسابداری با اکسل",
        excel_storage: "انبار با اکسل",
        excel_barcode: "بارکد با اکسل",
        excel_banking: "مغایرت بانکی با اکسل",
        excel_btn: "توضیحات",

        contact_title: "📞 تماس با ما",
        contact_phone: "شماره تماس",
        contact_email: "آدرس ایمیل",
        contact_address: "آدرس",
        contact_address_value: "هرمزگان - بندرعباس",
        contact_name_label: "نام و نام خانوادگی",
        contact_name_placeholder: "نام خود را وارد کنید...",
        contact_phone_label: "شماره تماس",
        contact_phone_placeholder: "شماره تماس خود را وارد کنید...",
        contact_message_label: "متن پیام",
        contact_message_placeholder: "نظر یا پیام خود را بنویسید...",
        contact_btn: "ارسال پیام",

        footer_text: "تمامی حقوق برای نرم‌افزار حسابداری مانگرو محفوظ است.",
        lang_switch: "EN",

        // ===== صفحه حسابداری با اکسل (accounting) =====
        accounting_page_title: "حسابداری با اکسل - نرم‌افزار حسابداری مانگرو",
        accounting_hero_title: "حسابداری با <span>اکسل</span>",
        accounting_hero_sub: "ارزان‌ترین و بهترین برنامه حسابداری با اکسل",
        accounting_hero_users: "با بیش از <strong>۵۸۰</strong> کاربر فعال تا سال ۱۳۹۷ در سراسر ایران",
        accounting_features_title: "✨ ویژگی‌های برنامه",
        accounting_features_desc: "برنامه حسابداری با اکسل، تمام نیازهای حسابداری شما را به ساده‌ترین شکل ممکن پوشش می‌دهد.",
        accounting_feature1_title: "تعریف حساب‌ها به دلخواه شما",
        accounting_feature1_desc: "امکان تعریف و ویرایش حساب‌های مالی بر اساس نیاز کسب‌وکار شما",
        accounting_feature2_title: "صدور سریع اسناد حسابداری",
        accounting_feature2_desc: "ثبت و صدور اسناد حسابداری با سرعت بالا و بدون پیچیدگی",
        accounting_feature3_title: "پیوست عکس یا PDF به هر سند",
        accounting_feature3_desc: "امکان ضمیمه کردن فایل‌های تصویری یا PDF به تمام اسناد",
        accounting_feature4_title: "تهیه تراز مالی دقیق و سریع",
        accounting_feature4_desc: "گزارش‌گیری تراز مالی، سود و زیان و صورت‌های مالی به‌صورت آنی",
        accounting_feature5_title: "چاپ اسناد و گزارش‌ها",
        accounting_feature5_desc: "چاپ مستقیم اسناد حسابداری و کلیه گزارش‌های مالی",
        accounting_feature6_title: "پشتیبان‌گیری خودکار روی سرور",
        accounting_feature6_desc: "ذخیره خودکار اطلاعات روی سرور و بازیابی آسان در هر زمان",
        accounting_feature7_title: "انتخاب زبان دلخواه برنامه",
        accounting_feature7_desc: "امکان تغییر زبان برنامه به فارسی، انگلیسی و زبان‌های دیگر",
        accounting_feature8_title: "استفاده از تقویم شمسی یا میلادی",
        accounting_feature8_desc: "انتخاب تقویم مورد نظر برای ثبت و گزارش‌گیری مالی",
        accounting_feature9_title: "کاردکس هر حساب با خروجی PDF",
        accounting_feature9_desc: "دریافت کاردکس حساب‌ها به صورت فایل PDF برای هر دوره مالی",
        accounting_gallery_title: "🖼️ تصاویر برنامه",
        accounting_download_btn: "دانلود برنامه حسابداری با اکسل",

        // ===== صفحه انبار خرید و فروش (storage) =====
        storage_page_title: "انبار خرید و فروش با اکسل - نرم‌افزار حسابداری مانگرو",
        storage_hero_title: "انبار خرید و فروش با <span>اکسل</span>",
        storage_hero_sub: "بهترین برنامه انبار خرید و فروش کالا با اکسل و امکان گزارش‌گیری سود به روش <strong>فایفو</strong><br>با بیش از <strong>۵۸۰</strong> کاربر فعال در سراسر ایران",
        storage_hero_badge: "محاسبه دقیق سود در بازه‌های زمانی دلخواه",
        storage_features_title: "✨ ویژگی‌های برنامه",
        storage_features_desc: "برای اولین بار بهترین برنامه انبار خرید و فروش کالا با اکسل و امکان گزارش‌گیری سود به روش فایفو توسط گروه نرم‌افزاری مانگرو تهیه گردیده است. با ثبت صحیح اطلاعات، گزارش دقیق سود به روش فایفو در بازه زمانی دلخواه به ریز هر کالا تهیه خواهد شد.",
        storage_feature1_title: "گزارش‌گیری سود به روش فایفو",
        storage_feature1_desc: "محاسبه دقیق سود به روش فایفو در بازه زمانی دلخواه به ریز هر کالا",
        storage_feature2_title: "محاسبه سود حتی یک روز",
        storage_feature2_desc: "امکان محاسبه سود در هر بازه زمانی حتی یک روز با دقت بالا",
        storage_feature3_title: "ثبت خودکار بدهکاران و طلبکاران",
        storage_feature3_desc: "ثبت خودکار حساب بدهکاران و طلبکاران حاصل از خرید و فروش",
        storage_feature4_title: "مدیریت حساب اشخاص",
        storage_feature4_desc: "استفاده جداگانه از حساب اشخاص (بدهکاران - طلبکاران) با امکان تهیه تراز",
        storage_feature5_title: "چاپ و خروجی گزارش‌ها",
        storage_feature5_desc: "امکان چاپ کلیه گزارش‌های مالی و انبار به صورت خروجی PDF",
        storage_feature6_title: "گزارش‌گیری پیشرفته",
        storage_feature6_desc: "تهیه گزارشات دقیق از وضعیت انبار، خرید و فروش و سوددهی کالاها",
        storage_gallery_title: "🖼️ تصاویر برنامه",
        storage_download_btn: "دانلود فایل برنامه انبار خرید و فروش",

        // ===== صفحه فروش با بارکد (barcode) =====
        barcode_page_title: "فروش محصول با بارکد در اکسل - نرم‌افزار حسابداری مانگرو",
        barcode_hero_title: "فروش محصول با <span>بارکد</span>",
        barcode_hero_sub: "بهترین برنامه فروش محصول با بارکد در اکسل<br>دیگر نیاز به خرید برنامه‌های گران‌قیمت و پیچیده ندارید.",
        barcode_hero_badge: "در دو نسخه ساده و پیشرفته",
        barcode_features_title: "✨ ویژگی‌های برنامه",
        barcode_features_desc: "برنامه فروش محصول با بارکد در اکسل، راهکاری ساده و کارآمد برای مدیریت فروش محصولات با استفاده از بارکد است. این برنامه در دو نسخه ساده و پیشرفته تهیه شده که به تناسب نیاز کاربران قابل استفاده است.",
        barcode_feature1_title: "خواندن بارکد محصولات",
        barcode_feature1_desc: "امکان خواندن بارکد محصولات با استفاده از اسکنر بارکد و ورود خودکار اطلاعات",
        barcode_feature2_title: "ثبت سریع فروش",
        barcode_feature2_desc: "ثبت فروش محصولات با کمترین زمان و بدون نیاز به وارد کردن دستی اطلاعات",
        barcode_feature3_title: "مدیریت موجودی انبار",
        barcode_feature3_desc: "بروزرسانی خودکار موجودی کالاها پس از هر فروش با استفاده از بارکد",
        barcode_feature4_title: "صدور فاکتور فروش",
        barcode_feature4_desc: "صدور فاکتور فروش به همراه جزئیات کامل محصولات فروخته شده",
        barcode_feature5_title: "گزارشات فروش",
        barcode_feature5_desc: "تهیه گزارشات فروش روزانه، هفتگی و ماهانه به تفکیک هر محصول",
        barcode_feature6_title: "چاپ بارکد محصولات",
        barcode_feature6_desc: "امکان طراحی و چاپ بارکد برای محصولات جدید به صورت حرفه‌ای",
        barcode_versions_title: "📦 نسخه‌های برنامه",
        barcode_version_simple_title: "نسخه ساده",
        barcode_version_simple_desc: "مناسب برای فروشگاه‌های کوچک و کاربرانی که نیاز به امکانات پایه فروش با بارکد دارند.",
        barcode_version_simple_badge: "مناسب برای شروع",
        barcode_version_advanced_title: "نسخه پیشرفته",
        barcode_version_advanced_desc: "مناسب برای فروشگاه‌های بزرگ با امکانات کامل گزارش‌گیری، مدیریت انبار و چاپ بارکد.",
        barcode_version_advanced_badge: "امکانات کامل",
        barcode_gallery_title: "🖼️ تصاویر برنامه",
        barcode_download_btn: "دانلود برنامه فروش با بارکد",

        // ===== صفحه مغایرت بانکی (banking) =====
        banking_page_title: "مغایرت بانکی با اکسل - نرم‌افزار حسابداری مانگرو",
        banking_hero_title: "مغایرت بانکی با <span>اکسل</span>",
        banking_hero_sub: "بهترین برنامه مغایرت بانکی با اکسل<br>با قابلیت کنترل بر اساس <strong>شماره و مبلغ</strong> و یا <strong>فقط مبلغ</strong>",
        banking_stat1_label: "آخرین ویرایش",
        banking_stat2_label: "تعداد دانلود نسخه قبلی",
        banking_hero_badge: "جدیدترین نسخه با امکانات پیشرفته",
        banking_features_title: "✨ ویژگی‌های برنامه",
        banking_features_desc: "برنامه مغایرت بانکی با اکسل، ابزاری قدرتمند برای تطابق سریع و دقیق صورت‌حساب‌های بانکی با دفاتر حسابداری شماست. با استفاده از این برنامه، مغایرت‌های بانکی را در کمترین زمان شناسایی و رفع کنید.",
        banking_feature1_title: "کنترل بر اساس شماره و مبلغ",
        banking_feature1_desc: "امکان تطابق تراکنش‌ها بر اساس شماره سند و مبلغ برای دقت بالا",
        banking_feature2_title: "کنترل فقط بر اساس مبلغ",
        banking_feature2_desc: "تطابق سریع تراکنش‌ها فقط با استفاده از مبلغ برای سرعت بیشتر",
        banking_feature3_title: "تطابق صورت‌حساب بانکی",
        banking_feature3_desc: "مقایسه خودکار صورت‌حساب بانکی با دفاتر حسابداری و شناسایی مغایرت‌ها",
        banking_feature4_title: "شناسایی خودکار تراکنش‌های تکراری",
        banking_feature4_desc: "تشخیص و حذف تراکنش‌های تکراری برای جلوگیری از خطا",
        banking_feature5_title: "گزارش‌گیری از مغایرت‌ها",
        banking_feature5_desc: "تهیه گزارشات کامل از مغایرت‌های بانکی به صورت دقیق و جامع",
        banking_feature6_title: "خروجی PDF و چاپ",
        banking_feature6_desc: "امکان خروجی گرفتن از گزارشات به صورت PDF و چاپ مستقیم",
        banking_gallery_title: "🖼️ تصاویر برنامه",
        banking_download_btn: "دانلود برنامه مغایرت بانکی با اکسل"
    },
    en: {
        // ===== Home page (index) =====
        nav_home: "Home",
        nav_features: "Features",
        nav_gallery: "Gallery",
        nav_video: "Video",
        nav_download: "Download",
        nav_excel: "Excel Software",
        nav_contact: "Contact",

        hero_title: "Accounting <span>Mangro</span> in Your Phone",
        hero_desc: "Experience all professional accounting features in the simplest way on your mobile",
        hero_btn: "Download App",

        feature1_title: "Accurate Reports",
        feature1_desc: "Access to all financial, cash, purchase and sales reports instantly",
        feature2_title: "Time Management",
        feature2_desc: "Deadlines for individuals, payable and receivable checks with smart alerts",
        feature3_title: "High Security",
        feature3_desc: "Your data is protected with the highest security standards",
        feature4_title: "Easy Access",
        feature4_desc: "All features on your phone, anytime, anywhere",

        gallery_title: "App Screenshots",

        video_title: "🎥 Introduction Video",
        video_btn: "More Tutorials",

        download_title: "📲 Download Now",
        download_ios: "iPhone Version",
        download_ios_sub: "(Coming Soon)",
        download_android: "Android Version",
        download_android_sub: "Download from Bazaar",
        download_pwa: "PWA Version",
        download_pwa_sub: "(Coming Soon)",

        excel_title: "Excel Software",
        excel_accounting: "Accounting with Excel",
        excel_storage: "Warehouse with Excel",
        excel_barcode: "Barcode with Excel",
        excel_banking: "Bank Reconciliation with Excel",
        excel_btn: "Details",

        contact_title: "📞 Contact Us",
        contact_phone: "Phone Number",
        contact_email: "Email Address",
        contact_address: "Address",
        contact_address_value: "Hormozgan - Bandar Abbas",
        contact_name_label: "Full Name",
        contact_name_placeholder: "Enter your name...",
        contact_phone_label: "Phone Number",
        contact_phone_placeholder: "Enter your phone number...",
        contact_message_label: "Message",
        contact_message_placeholder: "Write your message...",
        contact_btn: "Send Message",

        footer_text: "All rights reserved for Mangro Accounting Software",
        lang_switch: "FA",

        // ===== Accounting with Excel page =====
        accounting_page_title: "Accounting with Excel - Mangro Accounting Software",
        accounting_hero_title: "Accounting with <span>Excel</span>",
        accounting_hero_sub: "The cheapest and best accounting software with Excel",
        accounting_hero_users: "With over <strong>580</strong> active users since 2018 across Iran",
        accounting_features_title: "✨ Features",
        accounting_features_desc: "Excel accounting software covers all your accounting needs in the simplest way possible",
        accounting_feature1_title: "Define accounts as you like",
        accounting_feature1_desc: "Define and edit financial accounts based on your business needs",
        accounting_feature2_title: "Quick accounting documents",
        accounting_feature2_desc: "Record and issue accounting documents quickly and easily",
        accounting_feature3_title: "Attach photo or PDF to each document",
        accounting_feature3_desc: "Attach image or PDF files to all documents",
        accounting_feature4_title: "Accurate and fast balance sheet",
        accounting_feature4_desc: "Instantly generate balance sheet, profit and loss, and financial statements",
        accounting_feature5_title: "Print documents and reports",
        accounting_feature5_desc: "Direct printing of accounting documents and all financial reports",
        accounting_feature6_title: "Automatic backup on server",
        accounting_feature6_desc: "Automatically save data on server and easy recovery anytime",
        accounting_feature7_title: "Choose desired language",
        accounting_feature7_desc: "Change the software language to Persian, English and other languages",
        accounting_feature8_title: "Use Persian or Gregorian calendar",
        accounting_feature8_desc: "Select the desired calendar for registration and financial reporting",
        accounting_feature9_title: "Account card with PDF output",
        accounting_feature9_desc: "Get account cards as PDF file for each financial period",
        accounting_gallery_title: "🖼️ App Screenshots",
        accounting_download_btn: "Download Accounting with Excel",

        // ===== Warehouse (storage) page =====
        storage_page_title: "Warehouse Purchase and Sales with Excel - Mangro Accounting Software",
        storage_hero_title: "Warehouse Purchase and Sales with <span>Excel</span>",
        storage_hero_sub: "The best warehouse inventory and sales software with Excel and FIFO profit reporting<br>with over <strong>580</strong> active users across Iran",
        storage_hero_badge: "Accurate profit calculation in any desired time period",
        storage_features_title: "✨ Features",
        storage_features_desc: "For the first time, the best warehouse purchase and sales software with Excel and FIFO profit reporting has been developed by the Mangro software team. By correctly recording information, an accurate profit report using the FIFO method will be generated for each product in any desired time period",
        storage_feature1_title: "FIFO Profit Reporting",
        storage_feature1_desc: "Accurate profit calculation using FIFO method in any desired time period for each product",
        storage_feature2_title: "Calculate profit even for one day",
        storage_feature2_desc: "Calculate profit in any time period, even a single day, with high accuracy",
        storage_feature3_title: "Automatic recording of debtors and creditors",
        storage_feature3_desc: "Automatic recording of debtors and creditors accounts from purchases and sales",
        storage_feature4_title: "Manage individual accounts",
        storage_feature4_desc: "Separate use of individual accounts (debtors - creditors) with balance sheet capability",
        storage_feature5_title: "Print and export reports",
        storage_feature5_desc: "Print all financial and warehouse reports as PDF output",
        storage_feature6_title: "Advanced reporting",
        storage_feature6_desc: "Detailed reports on warehouse status, purchases, sales and product profitability",
        storage_gallery_title: "🖼️ App Screenshots",
        storage_download_btn: "Download Warehouse Purchase and Sales Program",

        // ===== Barcode page =====
        barcode_page_title: "Barcode Product Sales with Excel - Mangro Accounting Software",
        barcode_hero_title: "Barcode Product <span>Sales</span>",
        barcode_hero_sub: "The best barcode product sales software with Excel<br>No need to buy expensive and complex programs",
        barcode_hero_badge: "Available in simple and advanced versions",
        barcode_features_title: "✨ Features",
        barcode_features_desc: "Barcode product sales software with Excel is a simple and efficient solution for managing product sales using barcodes. This program is available in two versions, simple and advanced, to suit the needs of users",
        barcode_feature1_title: "Read product barcodes",
        barcode_feature1_desc: "Read product barcodes using a barcode scanner and automatic data entry",
        barcode_feature2_title: "Quick sales registration",
        barcode_feature2_desc: "Register product sales in the shortest time without manual data entry",
        barcode_feature3_title: "Inventory management",
        barcode_feature3_desc: "Automatically update inventory after each sale using barcodes",
        barcode_feature4_title: "Generate sales invoices",
        barcode_feature4_desc: "Generate sales invoices with complete details of sold products",
        barcode_feature5_title: "Sales reports",
        barcode_feature5_desc: "Generate daily, weekly and monthly sales reports by product",
        barcode_feature6_title: "Print product barcodes",
        barcode_feature6_desc: "Design and print barcodes for new products professionally",
        barcode_versions_title: "📦 Software Versions",
        barcode_version_simple_title: "Simple Version",
        barcode_version_simple_desc: "Suitable for small stores and users who need basic barcode sales features",
        barcode_version_simple_badge: "Good for start",
        barcode_version_advanced_title: "Advanced Version",
        barcode_version_advanced_desc: "Suitable for large stores with full reporting, inventory management and barcode printing features",
        barcode_version_advanced_badge: "Full features",
        barcode_gallery_title: "🖼️ App Screenshots",
        barcode_download_btn: "Download Barcode Sales Program",

        // ===== Bank Reconciliation (banking) page =====
        banking_page_title: "Bank Reconciliation with Excel - Mangro Accounting Software",
        banking_hero_title: "Bank Reconciliation with <span>Excel</span>",
        banking_hero_sub: "The best bank reconciliation software with Excel<br>with control based on <strong>number and amount</strong> or <strong>only amount</strong>",
        banking_stat1_label: "Last Update",
        banking_stat2_label: "Previous version downloads",
        banking_hero_badge: "Latest version with advanced features",
        banking_features_title: "✨ Features",
        banking_features_desc: "Bank reconciliation software with Excel is a powerful tool for quickly and accurately matching bank statements with your accounting books. Identify and resolve bank discrepancies in no time",
        banking_feature1_title: "Control by number and amount",
        banking_feature1_desc: "Match transactions based on document number and amount for high accuracy",
        banking_feature2_title: "Control by amount only",
        banking_feature2_desc: "Quickly match transactions using only the amount for greater speed",
        banking_feature3_title: "Bank statement matching",
        banking_feature3_desc: "Automatically compare bank statements with accounting books and identify discrepancies",
        banking_feature4_title: "Automatic duplicate transaction detection",
        banking_feature4_desc: "Detect and remove duplicate transactions to prevent errors",
        banking_feature5_title: "Discrepancy reporting",
        banking_feature5_desc: "Generate comprehensive reports on bank discrepancies accurately and thoroughly",
        banking_feature6_title: "PDF export and printing",
        banking_feature6_desc: "Export reports as PDF and print directly",
        banking_gallery_title: "🖼️ App Screenshots",
        banking_download_btn: "Download Bank Reconciliation with Excel"
    },
    ar: {
        // ===== الصفحة الرئيسية (index) =====
        nav_home: "الرئيسية",
        nav_features: "الميزات",
        nav_gallery: "المعرض",
        nav_video: "الفيديو",
        nav_download: "تحميل",
        nav_excel: "برنامج إكسل",
        nav_contact: "اتصل بنا",

        hero_title: "محاسبة <span>مانغرو</span> في هاتفك",
        hero_desc: "استمتع بجميع ميزات المحاسبة الاحترافية بأبسط طريقة على هاتفك المحمول.",
        hero_btn: "تحميل التطبيق",

        feature1_title: "تقارير دقيقة",
        feature1_desc: "الوصول الفوري إلى جميع التقارير المالية والنقدية والمشتريات والمبيعات.",
        feature2_title: "إدارة الوقت",
        feature2_desc: "مواعيد استحقاق الأفراد والشيكات الدائنة والمدينة مع تنبيهات ذكية.",
        feature3_title: "أمان عالٍ",
        feature3_desc: "بياناتك محمية بأعلى معايير الأمان.",
        feature4_title: "سهولة الوصول",
        feature4_desc: "جميع الميزات في هاتفك، في أي وقت وفي أي مكان.",

        gallery_title: "صور البرنامج",

        video_title: "🎥 فيديو تعريفي",
        video_btn: "المزيد من الدروس",

        download_title: "📲 حمّل الآن!",
        download_ios: "نسخة آيفون",
        download_ios_sub: "(قريباً)",
        download_android: "نسخة أندرويد",
        download_android_sub: "تحميل من بازار",
        download_pwa: "نسخة PWA",
        download_pwa_sub: "(قريباً)",

        excel_title: "برنامج إكسل",
        excel_accounting: "المحاسبة بإكسل",
        excel_storage: "المستودع بإكسل",
        excel_barcode: "الباركود بإكسل",
        excel_banking: "مطابقة البنك بإكسل",
        excel_btn: "تفاصيل",

        contact_title: "📞 اتصل بنا",
        contact_phone: "رقم الهاتف",
        contact_email: "البريد الإلكتروني",
        contact_address: "العنوان",
        contact_address_value: "هرمزگان - بندر عباس",
        contact_name_label: "الاسم الكامل",
        contact_name_placeholder: "أدخل اسمك...",
        contact_phone_label: "رقم الهاتف",
        contact_phone_placeholder: "أدخل رقم هاتفك...",
        contact_message_label: "الرسالة",
        contact_message_placeholder: "اكتب رسالتك...",
        contact_btn: "إرسال الرسالة",

        footer_text: "جميع الحقوق محفوظة لبرنامج محاسبة مانغرو.",
        lang_switch: "FA",

        // ===== صفحة المحاسبة بإكسل (accounting) =====
        accounting_page_title: "المحاسبة بإكسل - برنامج محاسبة مانغرو",
        accounting_hero_title: "المحاسبة بإكسل",
        accounting_hero_sub: "أرخص وأفضل برنامج محاسبة بإكسل",
        accounting_hero_users: "مع أكثر من <strong>580</strong> مستخدم نشط حتى عام 2018 في جميع أنحاء إيران",
        accounting_features_title: "✨ ميزات البرنامج",
        accounting_features_desc: "برنامج المحاسبة بإكسل يغطي جميع احتياجاتك المحاسبية بأبسط طريقة ممكنة.",
        accounting_feature1_title: "تعريف الحسابات كما تشاء",
        accounting_feature1_desc: "إمكانية تعريف وتعديل الحسابات المالية بناءً على احتياجات عملك",
        accounting_feature2_title: "إصدار سريع للمستندات المحاسبية",
        accounting_feature2_desc: "تسجيل وإصدار المستندات المحاسبية بسرعة ودون تعقيد",
        accounting_feature3_title: "إرفاق صورة أو PDF بكل مستند",
        accounting_feature3_desc: "إمكانية إرفاق ملفات صور أو PDF بجميع المستندات",
        accounting_feature4_title: "إعداد ميزانية مالية دقيقة وسريعة",
        accounting_feature4_desc: "إنشاء فوري للميزانية العمومية والأرباح والخسائر والقوائم المالية",
        accounting_feature5_title: "طباعة المستندات والتقارير",
        accounting_feature5_desc: "طباعة مباشرة للمستندات المحاسبية وجميع التقارير المالية",
        accounting_feature6_title: "نسخ احتياطي تلقائي على الخادم",
        accounting_feature6_desc: "حفظ البيانات تلقائياً على الخادم واستعادتها بسهولة في أي وقت",
        accounting_feature7_title: "اختيار اللغة المطلوبة",
        accounting_feature7_desc: "تغيير لغة البرنامج إلى الفارسية والإنجليزية واللغات الأخرى",
        accounting_feature8_title: "استخدام التقويم الهجري أو الميلادي",
        accounting_feature8_desc: "اختيار التقويم المطلوب للتسجيل والتقارير المالية",
        accounting_feature9_title: "بطاقة الحساب مع إخراج PDF",
        accounting_feature9_desc: "الحصول على بطاقات الحساب كملف PDF لكل فترة مالية",
        accounting_gallery_title: "🖼️ صور البرنامج",
        accounting_download_btn: "تحميل برنامج المحاسبة بإكسل",

        // ===== صفحة المستودع (storage) =====
        storage_page_title: "المستودع (الشراء والبيع) بإكسل - برنامج محاسبة مانغرو",
        storage_hero_title: "المستودع (الشراء والبيع) بإكسل",
        storage_hero_sub: "أفضل برنامج لإدارة مخزون المستودع والبيع بإكسل مع إمكانية تقرير الأرباح بطريقة FIFO<br>مع أكثر من <strong>580</strong> مستخدم نشط في جميع أنحاء إيران",
        storage_hero_badge: "حساب دقيق للأرباح في فترات زمنية مخصصة",
        storage_features_title: "✨ ميزات البرنامج",
        storage_features_desc: "لأول مرة، تم إعداد أفضل برنامج لإدارة مخزون المستودع والبيع بإكسل مع إمكانية تقرير الأرباح بطريقة FIFO بواسطة فريق برمجيات مانغرو. من خلال تسجيل المعلومات بشكل صحيح، سيتم إعداد تقرير دقيق للأرباح باستخدام طريقة FIFO لكل منتج في أي فترة زمنية مطلوبة.",
        storage_feature1_title: "تقرير الأرباح بطريقة FIFO",
        storage_feature1_desc: "حساب دقيق للأرباح بطريقة FIFO في أي فترة زمنية لكل منتج",
        storage_feature2_title: "حساب الأرباح حتى ليوم واحد",
        storage_feature2_desc: "إمكانية حساب الأرباح في أي فترة زمنية حتى ليوم واحد بدقة عالية",
        storage_feature3_title: "تسجيل تلقائي للمدينين والدائنين",
        storage_feature3_desc: "تسجيل تلقائي لحسابات المدينين والدائنين الناتجة عن الشراء والبيع",
        storage_feature4_title: "إدارة حسابات الأفراد",
        storage_feature4_desc: "استخدام منفصل لحسابات الأفراد (المدينون - الدائنون) مع إمكانية إعداد الميزانية",
        storage_feature5_title: "طباعة وتصدير التقارير",
        storage_feature5_desc: "إمكانية طباعة جميع التقارير المالية والمستودعات كملف PDF",
        storage_feature6_title: "تقارير متقدمة",
        storage_feature6_desc: "تقارير مفصلة عن حالة المستودع والمشتريات والمبيعات وربحية المنتجات",
        storage_gallery_title: "🖼️ صور البرنامج",
        storage_download_btn: "تحميل برنامج المستودع (الشراء والبيع)",

        // ===== صفحة الباركود (barcode) =====
        barcode_page_title: "مبيعات المنتجات بالباركود بإكسل - برنامج محاسبة مانغرو",
        barcode_hero_title: "مبيعات المنتجات بالباركود",
        barcode_hero_sub: "أفضل برنامج لبيع المنتجات بالباركود بإكسل<br>لا حاجة لشراء برامج باهظة الثمن ومعقدة.",
        barcode_hero_badge: "متوفر في نسختين بسيطة ومتقدمة",
        barcode_features_title: "✨ ميزات البرنامج",
        barcode_features_desc: "برنامج مبيعات المنتجات بالباركود بإكسل هو حل بسيط وفعال لإدارة مبيعات المنتجات باستخدام الباركود. تم إعداد هذا البرنامج في نسختين بسيطة ومتقدمة لتتناسب مع احتياجات المستخدمين.",
        barcode_feature1_title: "قراءة باركود المنتجات",
        barcode_feature1_desc: "قراءة باركود المنتجات باستخدام ماسح الباركود وإدخال البيانات تلقائياً",
        barcode_feature2_title: "تسجيل سريع للمبيعات",
        barcode_feature2_desc: "تسجيل مبيعات المنتجات في أقل وقت دون الحاجة إلى إدخال بيانات يدوي",
        barcode_feature3_title: "إدارة مخزون المستودع",
        barcode_feature3_desc: "تحديث تلقائي للمخزون بعد كل عملية بيع باستخدام الباركود",
        barcode_feature4_title: "إصدار فواتير المبيعات",
        barcode_feature4_desc: "إصدار فواتير المبيعات مع تفاصيل كاملة للمنتجات المباعة",
        barcode_feature5_title: "تقارير المبيعات",
        barcode_feature5_desc: "تقارير مبيعات يومية وأسبوعية وشهرية لكل منتج",
        barcode_feature6_title: "طباعة باركود المنتجات",
        barcode_feature6_desc: "تصميم وطباعة باركود للمنتجات الجديدة بشكل احترافي",
        barcode_versions_title: "📦 نسخ البرنامج",
        barcode_version_simple_title: "النسخة البسيطة",
        barcode_version_simple_desc: "مناسبة للمتاجر الصغيرة والمستخدمين الذين يحتاجون إلى ميزات أساسية لبيع الباركود.",
        barcode_version_simple_badge: "مناسبة للبدء",
        barcode_version_advanced_title: "النسخة المتقدمة",
        barcode_version_advanced_desc: "مناسبة للمتاجر الكبيرة مع ميزات كاملة للتقارير وإدارة المخزون وطباعة الباركود.",
        barcode_version_advanced_badge: "ميزات كاملة",
        barcode_gallery_title: "🖼️ صور البرنامج",
        barcode_download_btn: "تحميل برنامج الباركود",

        // ===== صفحة مطابقة البنك (banking) =====
        banking_page_title: "مطابقة البنك بإكسل - برنامج محاسبة مانغرو",
        banking_hero_title: "مطابقة البنك بإكسل",
        banking_hero_sub: "أفضل برنامج لمطابقة البنك بإكسل<br>مع إمكانية التحكم بناءً على <strong>الرقم والمبلغ</strong> أو <strong>المبلغ فقط</strong>",
        banking_stat1_label: "آخر تحديث",
        banking_stat2_label: "عدد تحميلات النسخة السابقة",
        banking_hero_badge: "أحدث إصدار بميزات متقدمة",
        banking_features_title: "✨ ميزات البرنامج",
        banking_features_desc: "برنامج مطابقة البنك بإكسل هو أداة قوية لمطابقة كشوفات البنك مع دفاتر المحاسبة الخاصة بك بسرعة ودقة. حدد وأصلح التناقضات البنكية في أقل وقت.",
        banking_feature1_title: "التحكم بالرقم والمبلغ",
        banking_feature1_desc: "مطابقة المعاملات بناءً على رقم المستند والمبلغ لدقة عالية",
        banking_feature2_title: "التحكم بالمبلغ فقط",
        banking_feature2_desc: "مطابقة سريعة للمعاملات باستخدام المبلغ فقط لسرعة أكبر",
        banking_feature3_title: "مطابقة كشف الحساب البنكي",
        banking_feature3_desc: "مقارنة تلقائية لكشوفات البنك مع دفاتر المحاسبة وتحديد التناقضات",
        banking_feature4_title: "كشف تلقائي للمعاملات المكررة",
        banking_feature4_desc: "اكتشاف وإزالة المعاملات المكررة لمنع الأخطاء",
        banking_feature5_title: "تقارير التناقضات",
        banking_feature5_desc: "إنشاء تقارير شاملة عن التناقضات البنكية بدقة وشمولية",
        banking_feature6_title: "تصدير PDF وطباعة",
        banking_feature6_desc: "تصدير التقارير بصيغة PDF والطباعة المباشرة",
        banking_gallery_title: "🖼️ صور البرنامج",
        banking_download_btn: "تحميل برنامج مطابقة البنك بإكسل"
    }
};